FROM golang:1.22.2

WORKDIR /usr/src/app

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .

RUN go build -o /usr/src/app/tinystore

RUN ls -la /usr/src/app/tinystore

CMD ["./tinystore", "-config", "configs/nodes.json", "-capacity", "100", "-verbose"]