version: '3'

services:
  
  cacheserver0:
   
    hostname: cacheserver0
    build:
      context: .
      dockerfile: Dockerfile.server
    restart: unless-stopped
    environment:
      GIN_MODE: release
      GODEBUG: x509sha1=1 

  cacheserver1:
    
    hostname: cacheserver1
    build:
      context: . 
      dockerfile: Dockerfile.server
    restart: unless-stopped
    environment: 
      GIN_MODE: release
      GODEBUG: x509sha1=1   

  cacheserver2:
    
    hostname: cacheserver2
    build:
      context: . 
      dockerfile: Dockerfile.server
    restart: unless-stopped
    environment: 
      GIN_MODE: release
      GODEBUG: x509sha1=1

  cacheserver3:
    
    hostname: cacheserver3
    build:
      context: . 
      dockerfile: Dockerfile.server
    restart: unless-stopped
    environment: 
      GIN_MODE: release
      GODEBUG: x509sha1=1   

  cacheserver4:
    
    hostname: cacheserver4
    build:
      context: . 
      dockerfile: Dockerfile.server
    restart: unless-stopped
    environment: 
      GIN_MODE: release
      GODEBUG: x509sha1=1   